### ISSUE TITLE
Not working to spawn a simple Instance

### ISSUE THREAD

**Issue by teknologista** [jaxxstorm/pulumi-scaleway#29]
Setting up a simple instance with a private network, block storage and Security Group fails.

This is the output:

 ```
    Type                                     Name         Status                  Info
 +   pulumi:pulumi:Stack                      pulum-dev    **creating failed**     1 error
 +   ├─ scaleway:index:InstanceIp             openreplay   created
 +   ├─ scaleway:index:InstanceVolume         data         created
 +   ├─ scaleway:index:InstanceSecurityGroup  open-replay  created
 +   └─ scaleway:index:InstanceServer         openreplay   **creating failed**     1 error

Diagnostics:
  scaleway:index:InstanceServer (openreplay):
    error: 1 error occurred:
    	* creating urn:pulumi:dev::pulum::scaleway:index/instanceServer:InstanceServer::openreplay: 1 error occurred:
    	* scaleway-sdk-go: resource unknown with ID  is not found

  pulumi:pulumi:Stack (pulum-dev):
    error: update failed

Resources:
    + 4 created
```

Everything seems to be created and shows up on Scaleway web console though...

The if we do a `pulumi refresh`:

```
Diagnostics:
  scaleway:index:InstanceServer (openreplay):
    error: Preview failed: transport is closing

  pulumi:pulumi:Stack (pulum-dev):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1c69a0e]
    goroutine 66 [running]:
    github.com/scaleway/terraform-provider-scaleway/scaleway.(*privateNICsHandler).get(0xc000961480, {0xc0006d0090, 0x2d})
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway@v1.17.1-0.20211230161835-24df682dbb8e/scaleway/helpers_instance.go:391 +0xce
    github.com/scaleway/terraform-provider-scaleway/scaleway.(*privateNICsHandler).set(0xc000961480, 0x1faa50c)
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway@v1.17.1-0.20211230161835-24df682dbb8e/scaleway/helpers_instance.go:374 +0x11d
    github.com/scaleway/terraform-provider-scaleway/scaleway.resourceScalewayInstanceServerRead({0x22e7a90, 0xc000458840}, 0xc000452080, {0x1d6f500, 0xc000a723b0})
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway@v1.17.1-0.20211230161835-24df682dbb8e/scaleway/resource_instance_server.go:602 +0x1766
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0007bc9c0, {0x22e7a58, 0xc0000400c8}, 0x24, {0x1d6f500, 0xc000a723b0})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20211230170131-3a7c83bfab87/helper/schema/resource.go:348 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0007bc9c0, {0x22e7a58, 0xc0000400c8}, 0xc0007e7520, {0x1d6f500, 0xc000a723b0})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20211230170131-3a7c83bfab87/helper/schema/resource.go:625 +0x35b
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Refresh({0xc000632180}, {0x1fbf508, 0x18}, {0x22e8510, 0xc000baee80})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.16.0/pkg/tfshim/sdk-v2/provider.go:125 +0x155
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc0001ee800, {0x22e7ac8, 0xc0006148a0}, 0xc00061a280)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.16.0/pkg/tfbridge/provider.go:941 +0x651
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x22e7ac8, 0xc0006148a0}, {0x1f2b920, 0xc00061a280})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.22.0/proto/go/provider.pb.go:2638 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x22e7ac8, 0xc000614630}, {0x1f2b920, 0xc00061a280}, 0xc000626120, 0xc0003f4600)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x425
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1f6c8c0, 0xc0001ee800}, {0x22e7ac8, 0xc000614630}, 0xc000622300, 0xc0005941a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.22.0/proto/go/provider.pb.go:2640 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00083c000, {0x22fe1d0, 0xc0005f4000}, 0xc000596360, 0xc00083a330, 0x2ce4878, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0xc8f
    google.golang.org/grpc.(*Server).handleStream(0xc00083c000, {0x22fe1d0, 0xc0005f4000}, 0xc000596360, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x294

    error: preview failed
```

This is on a Typescript project, on a MacBook Pro Intel running MacOS 12.2.1 and NodeJS v12.18.2

**Comment by jaxxstorm** [comment]
Hi there! can you share the code you used, so I can try repro this?

**Comment by teknologista** [comment]
Hi @jaxxstorm ,

Some ids are obfuscated...

```
import * as pulumi from "@pulumi/pulumi";
import { local, remote, types } from "@pulumi/command";
import * as scaleway from "@jaxxstorm/pulumi-scaleway";
import * as fs from "fs";
import { vpnHTTPSAllowRules, vpnSSHAllowRules } from "./lib/support";
import { cloudConfig } from "./lib/templates";

const config = new pulumi.Config();

const publicIp = new scaleway.InstanceIp("newInstance", {});

// Get info by security group id
const firewall = new scaleway.InstanceSecurityGroup("newInstance", {
  inboundDefaultPolicy: "drop",
  outboundDefaultPolicy: "accept",
  enableDefaultSecurity: false,
  inboundRules: [
    {
      action: "accept",
      ipRange: "192.168.74.0/24",
      protocol: "TCP",
      port: 443,
    },
    ...vpnSSHAllowRules,
    ...vpnHTTPSAllowRules,
  ],
  stateful: true,
});

const data = new scaleway.InstanceVolume("data", {
  sizeInGb: 500,
  type: "b_ssd",
});

const privateNetwork = pulumi.output(
  scaleway.getVpcPrivateNetwork({
    privateNetworkId: "fr-par-2/XXXXXXXXXXXXXXXXXXX",
  })
);

const server = new scaleway.InstanceServer(
  "openreplay",
  {
    type: "GP1-S",
    image: "ubuntu_focal",
    ipId: publicIp.id,
    securityGroupId: firewall.id,
    privateNetworks: [
      {
        pnId: privateNetwork.id,
      },
    ],
    tags: ["pulumi"],
    userData: {
      "cloud-init": cloudConfig,
    },
    additionalVolumeIds: [data.id],
  },
  { replaceOnChanges: ["type", "image"] }
);

const pnic01 = new scaleway.InstancePrivateNic("newInstance_pnic01", {
  privateNetworkId: "fr-par-2/XXXXXXXXXXXXXXXXXXX",
  serverId: server.id,
});

const connection: types.input.remote.ConnectionArgs = {
  host: server.publicIp,
  user: "root",
  privateKey: fs.readFileSync(`./files/tf_scaleway`).toString("utf8"),
};

const hostname = new remote.Command("hostname", {
  connection,
  create: "hostname",
});

new remote.Command(
  "remotePrivateIP",
  {
    connection,
    create: pulumi.interpolate`echo ${server.privateIp} > private_ip.txt`,
    delete: `rm ./infos/private_ip.txt`,
  },
  { deleteBeforeReplace: true }
);

new local.Command(
  "localPrivateIP",
  {
    create: pulumi.interpolate`echo ${server.privateIp} > ./infos/private_ip.txt`,
    delete: `rm ./infos/private_ip.txt`,
  },
  { deleteBeforeReplace: true }
);

new local.Command(
  "localPublicIP",
  {
    create: pulumi.interpolate`echo ${server.privateIp} > ./infos/public_ip.txt`,
    delete: `rm ./infos/public_ip.txt`,
  },
  { deleteBeforeReplace: true }
);
```

**Comment by teknologista** [comment]
Hi @jaxxstorm ,

Fixed it by removing the blocks:

```
const privateNetwork = pulumi.output(
  scaleway.getVpcPrivateNetwork({
    privateNetworkId: "fr-par-2/XXXXXXXXXXXXXXXXXXX",
  })
);

```

and

```
  privateNetworks: [
      {
        pnId: privateNetwork.id,
      },
    ],

```
